spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tmall_springboot?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  redis:
    database: 1
    timeout: 3000
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-wait: -1
        max-idle: 8
        min-idle: 0

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # 开启消息确认机制 confirm 异步
    publisher-confirm-type: correlated
    # 消息开启手动确认
    listener:
      direct:
        acknowledge-mode: manual
    publisher-returns: true

server:
  port: 8888


    # wzh新增配置
  # 配置swagger
swagger:
  enable: true

rabbit:
  #工作
  queueWork: queue_Work
  queueFanout1: queue_Fanout1
  queueFanout2: queue_Fanout2
  exchangeFanout: exchange_fanout
  queueTopic1: queue_Topic1
  queueTopic2: queue_Topic2
  exchangeTopic: exchange_topic
  queueConfirm: queue_Confirm
  queueReturn: queue_Return
  exchangeReturn: exchange_Return



